on: [push, pull_request]
name: tibTheme
jobs:
  tibTheme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 8.0
            database: mysql
            test: 'test'
          - application: ojs
            php-version: 8.0
            database: pgsql
            test: 'test'
          - application: ojs
            php-version: 8.1
            database: mysql
            test: 'test'
          - application: ojs
            php-version: 8.1
            database: pgsql
            test: 'test'
          - application: ojs
            php-version: 8.2
            database: mysql
            test: 'test'
          - application: ojs
            php-version: 8.2
            database: pgsql
            test: 'test'

    name: tibTheme
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
          node_version: 12
          branch: stable-3_3_0
          repository: pkp
          plugin: true
          dataset_inject: true
